import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import parseOpml from "../lib/opml-parser";

export default function Home(props) {
  function prLink(id){
    return "https://www.podcastrepublic.net/podcast/" + id;
  }

	return (
		<div className={styles.container}>
			<Head>
				<title>My podcasts</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>My podcasts</h1>

				<table>
          <tbody>
			    {
            props.podcasts.children.map((c)=>(
              <tr id={c.pr_id}>
                <td class="img" valign="top">
                  <a href={prLink(c.pr_id)} target="_blank">
                    <img src={c.pr_artwork} width="100px" height="100px" />
                  </a>
                </td>
                <td>
                  Podcast: <a href={prLink(c.pr_id)} target="_blank"><b>{c.title}</b></a><br/>
                  Category: <b>{c.category.replace("/", " ").replace("/", " ")}</b> <br/>
                  Description: <b>{c.pr_desc}</b> <br/>
                </td>
              </tr>
            ))
          }
        </tbody>
        </table>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}

export async function getStaticProps() {
  var podcasts = await parseOpml();
  return {
      props: {
          podcasts: podcasts 
      }
  };
}
